### ISSUE TITLE
How do I display an image in my notification?

### ISSUE THREAD

**Issue by mrousavy** [react-native-push-notification/ios#153]
# Question

Hi! I'm sending an `imageUrl` property to my user via the Firebase Cloud Messaging API, so my request looks like this:

```js
token: token,
notification: {
	imageUrl: imageUrl,
	title: chatTitle,
	body: messagePrefix + message.message,
}
```

Now how do I display the image (`imageUrl`) in my notification?

**Comment by AmnaHijjawi** [comment]
+1

**Comment by thuynt99** [comment]
I can't not show image in foreground but i can show in background? Any solution to fix that?

**Comment by andrew-stupchuk** [comment]
+1
@thuynt99  did you a find a way to show it?

**Comment by rjuevesano** [comment]
+1

**Comment by sujitgawas19** [comment]
+1
any update on this?

**Comment by BunHouth** [comment]
please kindly check this https://github.com/react-native-push-notification-ios/push-notification-ios/issues/255#issuecomment-793955531

**Comment by Naturalclar** [comment]
Rich notification with Image Support has been added in v1.9.0 :tada:

**Comment by vibhumishra74** [comment]
token: token,
notification: {
	imageUrl: imageUrl,
	title: chatTitle,
	body: messagePrefix + message.message,
}

replace imageUrl with image and one valid url with 2:1 aspect ratio
