### ISSUE TITLE
[FEATURE QUESTION] Does this package has support for `criticalAlerts`?

### ISSUE THREAD

**Issue by Roka20012** [react-native-push-notification/ios#225]
Check this link -> [apple critical alerts](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/generating_a_remote_notification)

My question is, does this package support this feature?

**Comment by Naturalclar** [comment]
@Roka20012 Thanks for raising the issue.
At the moment this package does not support apple critical alerts, but it would be nice to implement it for the future release.
I'll look into it.

**Comment by dan-lee** [comment]
I tested critical alerts and they just work without any extra implementation.

The `.entitlements` file needed an extra key though:

```xml
  <key>com.apple.developer.usernotifications.critical-alerts</key>
  <true/>
```
