### ISSUE TITLE
Can i display image on push notification?

### ISSUE THREAD

**Issue by thuynt99** [react-native-push-notification/ios#255]
For ios: 
       - how can i display push when app in FG?

**Comment by sujitgawas19** [comment]
Hey.. did you figure out how to display image when the app is in foreground?
I am facing the same problem.

**Comment by thuynt99** [comment]
@sujitgawas19  No, I can't show image in FG.
I am looking for solution!

**Comment by BunHouth** [comment]
> @sujitgawas19 No, I can't show image in FG.
> I am looking for solution!

![IMG_2CDDBF18A6C3-1](https://user-images.githubusercontent.com/8031851/110476389-45d08a80-8125-11eb-884a-93a10fddc2dc.jpeg)

You want something like that?

**Comment by sujitgawas19** [comment]
Ya. How did you do that?
Was the app in foreground?

**Comment by BunHouth** [comment]
> @BunHouth Ya. How did you do that?
> Was the app in foreground?

something like that?

This for local notification only.

https://user-images.githubusercontent.com/8031851/110482785-5d5f4180-812c-11eb-8984-54243d1f553f.mov

**Comment by sujitgawas19** [comment]
@BunHouth Can you share the code to display the local push notifications?

**Comment by BunHouth** [comment]
> @BunHouth Can you share the code to display the local push notifications?

you can found example code here => https://github.com/aasatech/rn-push-notification-image
fork repo => https://github.com/aasatech/push-notification-ios#local-notification-image

happy coding :)

**Comment by BunHouth** [comment]
> @BunHouth Great.
> Why don't you create a PR for this?

I think that feature is optional.

**Comment by vuletuanbt** [comment]
> > @BunHouth Great.
> > Why don't you create a PR for this?
> 
> I think that feature is optional.

Could you create PR for this feature ?  I think more people need to see this

**Comment by BunHouth** [comment]
> > > @BunHouth Great.
> > > Why don't you create a PR for this?
> > 
> > 
> > I think that feature is optional.
> 
> Could you create PR for this feature ? I think more people need to see this

That feature is optional, because we just using it for local notification only. 
You can using my fork repo or using patch package instead.

**Comment by vuletuan** [comment]
Okie. I got it

**Comment by vuletuanbt** [comment]
I created PR for this issue, please check it out https://github.com/react-native-push-notification-ios/push-notification-ios/pull/272

**Comment by thuynt99** [comment]
@BunHouth  Amazingly, I was able to show the picture while in FG. thank you very much!!!!!!!!

**Comment by ghostknow** [comment]
@BunHouth How can I show image with remote notification, thanks

**Comment by BunHouth** [comment]
> @BunHouth How can I show image with remote notification, thanks

for remote notification, please check this https://rnfirebase.io/messaging/ios-notification-images#step-1---add-a-notification-service-extension

**Comment by trungtin2222** [comment]
> @BunHouth Amazingly, I was able to show the picture while in FG. thank you very much!!!!!!!!

Hi Thuy, can i have your code ? i tried but not work :(

**Comment by thuynt99** [comment]
@trungtin2222 what version react native do you use???

**Comment by trungtin2222** [comment]
> @trungtin2222 what version react native do you use???

I use react-native@0.63.3

**Comment by BunHouth** [comment]
> > @trungtin2222 what version react native do you use???
> 
> I use react-native@0.63.3

@trungtin2222 you can check this thread first

https://github.com/react-native-push-notification-ios/push-notification-ios/issues/255#issuecomment-793955531

[react-native-push-notification-ios](https://github.com/react-native-push-notification-ios/push-notification-ios) is not support local image notification.

**Comment by trungtin2222** [comment]
> > > @trungtin2222 what version react native do you use???
> > 
> > 
> > I use react-native@0.63.3
> 
> @trungtin2222 you can check this thread first
> 
> [#255 (comment)](https://github.com/react-native-push-notification-ios/push-notification-ios/issues/255#issuecomment-793955531)
> 
> [react-native-push-notification-ios](https://github.com/react-native-push-notification-ios/push-notification-ios) is not support local image notification.

hi @BunHouth, i checked your comment, i was used your code but it's not work for me, i try to check AppDelegate.m but i don't have more information

**Comment by BunHouth** [comment]
> > > > @trungtin2222 what version react native do you use???
> > > 
> > > 
> > > I use react-native@0.63.3
> > 
> > 
> > @trungtin2222 you can check this thread first
> > [#255 (comment)](https://github.com/react-native-push-notification-ios/push-notification-ios/issues/255#issuecomment-793955531)
> > [react-native-push-notification-ios](https://github.com/react-native-push-notification-ios/push-notification-ios) is not support local image notification.
> 
> hi @BunHouth, i checked your comment, i was used your code but it's not work for me, i try to check AppDelegate.m but i don't have more information

if you want local notification work, you need to change your package.json
`"@react-native-community/push-notification-ios": "^1.8.0"` to
` "@react-native-community/push-notification-ios": "aasatech/push-notification-ios",`

**Comment by trungtin2222** [comment]
> > > > > @trungtin2222 what version react native do you use???
> > > > 
> > > > 
> > > > I use react-native@0.63.3
> > > 
> > > 
> > > @trungtin2222 you can check this thread first
> > > [#255 (comment)](https://github.com/react-native-push-notification-ios/push-notification-ios/issues/255#issuecomment-793955531)
> > > [react-native-push-notification-ios](https://github.com/react-native-push-notification-ios/push-notification-ios) is not support local image notification.
> > 
> > 
> > hi @BunHouth, i checked your comment, i was used your code but it's not work for me, i try to check AppDelegate.m but i don't have more information
> 
> if you want local notification work, you need to change your package.json
> `"@react-native-community/push-notification-ios": "^1.8.0"` to
> ` "@react-native-community/push-notification-ios": "aasatech/push-notification-ios",`

I think you should create PR for this feature, my app still not work with image, i think this issue happening on M1 devices :(

**Comment by trungtin2222** [comment]
it's work in intel devices, many thanks @BunHouth

**Comment by Naturalclar** [comment]
rich notification support with images has been added in v1.9.0 :tada:

**Comment by danishsaleem0** [comment]
image not showing in background
