### ISSUE TITLE
Notifications are not receiving on iphone 12.Rest of the devices are getting the notification

### ISSUE THREAD

**Issue by ZaidQ797** [react-native-push-notification/ios#288]
Hello! Folks.I'm trying to send notification from firebase to app but I found something weird that notifications are coming upto iphone 11 but on iphone 12 not.Can anybody tell me whats can be the reason

**Comment by ididlive** [comment]
What are the package versions that you are using? From this repo and also the https://github.com/zo0r/react-native-push-notification

**Comment by ZaidQ797** [comment]
I updated the firebase version and it worked
