### ISSUE TITLE
Can i display image notification in foreground ???

### ISSUE THREAD

**Issue by trungtin2222** [react-native-push-notification/ios#307]
Hi all, i tried to find another issues related to image notification in this library (#255), and i fixed but not work for me, so i create this issue for seek help from people.

This is my code:

```
const notifyiOS = () => {
        PushNotificationIOS.addNotificationRequest({
            id: '123123',
            title: 'Hello react native',
            body: 'Example with image',
            userInfo: {
                image:
                    'https://cdn.pixabay.com/photo/2018/01/21/01/46/architecture-3095716_960_720.jpg',
            },
        });
    };
```

![Screen Shot 2021-07-18 at 03 44 15](https://user-images.githubusercontent.com/72376596/126048958-17128b7e-fe6f-4f3f-b29a-b595f74a06d1.png)

and 

```
const options = {
                title: 'Notification Title',
                message: 'Notification Body',
                userInfo: {
                    image: 'https://www.online-tech-tips.com/wp-content/uploads/2016/03/widescreen-iphone-photo.jpg',
                },
            };
PushNotification.localNotification(options);
```

![Screen Shot 2021-07-18 at 03 44 32](https://user-images.githubusercontent.com/72376596/126048962-abd4456f-d822-4491-9f79-4aca24db9d85.png)
i'm using 

`
"@react-native-community/push-notification-ios": "^1.8.0",
"react-native-push-notification": "^7.4.0",
`

Many thank

**Comment by Naturalclar** [comment]
Rich notification with Image Support has been added in v1.9.0 :tada:
