### ISSUE TITLE
How can I prevent to receive notification when app in foreground?

### ISSUE THREAD

**Issue by AlanWen2016** [react-native-push-notification/ios#344]
PM doesn' t want to get notification when app in foreground.How can I prevent to receive notification when app in foreground?

**Comment by Wimmind** [comment]
@AlanWen2016 send local notification, when the remote came

**Comment by tavour-frank** [comment]
you can change the behavior in your app delegate:

```
// Called when a notification is delivered to a foreground app.
  -(void)userNotificationCenter:(UNUserNotificationCenter *)center willPresentNotification:(UNNotification *)notification withCompletionHandler:(void (^)(UNNotificationPresentationOptions options))completionHandler
  {
    completionHandler(UNNotificationPresentationOptionSound | UNNotificationPresentationOptionAlert | UNNotificationPresentationOptionBadge);
  }
```
https://developer.apple.com/documentation/usernotifications/unusernotificationcenterdelegate/1649518-usernotificationcenter?language=objc

sounds like you'll want [UNNotificationPresentationOptionNone](https://developer.apple.com/documentation/usernotifications/unnotificationpresentationoptionnone?language=objc) (  other options documented [here](https://developer.apple.com/documentation/usernotifications/unnotificationpresentationoptions?language=objc))
