### ISSUE TITLE
How to import RNCPushNotificationIOS into Swift file

### ISSUE THREAD

**Issue by ThushalIntervest** [react-native-push-notification/ios#387]
<img width="946" alt="Screenshot 2023-01-04 at 14 56 20" src="https://user-images.githubusercontent.com/100312355/210524024-c20b35ea-0943-4a0d-b464-6d92173058fd.png">

I convert my AppDelegate.mm file to AppDelegate.swift. Now I am facing the problem of importing RNCPushNotificationIOS to the project.

**Comment by wojtekmaj** [comment]
@ThushalIntervest Would you be so kind to share your full solution? I am absolutely clueless in that matter.
