### ISSUE TITLE
Where is the changelog from this library?

### ISSUE THREAD

**Issue by rafaelsevla** [react-native-push-notification/ios#435]
When I search by "@react-native-community/push-notification-ios changelog" I only find this one: https://github.com/zo0r/react-native-push-notification/blob/master/CHANGELOG.md

**Comment by gbiktx** [comment]
You can see what changed in the [release notes](https://github.com/react-native-push-notification/ios/releases)

**Comment by rafaelsevla** [comment]
thanks
